--pass pgadmin: jujutsu

CREATE TABLE CAMION (
    ID_CAMION SERIAL PRIMARY KEY,
    PATENTE VARCHAR(10) NULL
);
----------------------------------------

CREATE TABLE CIUDAD (
    ID_CIUDAD SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(200)
);


CREATE TABLE RUTA (
    ID_RUTA SERIAL  PRIMARY KEY,
    DETALLE VARCHAR(200) NULL,
    FK_ID_CIUDAD INT,
    FOREIGN KEY(FK_ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD)

);
------------------------------------------

CREATE TABLE TIPO_USUARIO (
	ID_TIPO_USUARIO SERIAL PRIMARY KEY,
	DESCRIPCION VARCHAR(200)
);


CREATE TABLE USUARIO (
	ID_USUARIO SERIAL PRIMARY KEY,
	RUT VARCHAR(12),
	NOMBRES VARCHAR(200),
	APELLIDOS VARCHAR(200),
	FK_ID_TIPO_USUARIO INT,
	FOREIGN KEY (FK_ID_TIPO_USUARIO) REFERENCES TIPO_USUARIO(ID_TIPO_USUARIO)
);

------------------------------------------

CREATE TABLE TIPO_PRODUCTO (
	ID_TIPO_PRODUCTO SERIAL PRIMARY KEY,
	DETALLE VARCHAR(200)
);


CREATE TABLE PRODUCTO ( 
	ID_PRODUCTO SERIAL PRIMARY KEY,
	DESCRIPCION VARCHAR(200) NULL,
	FK_ID_TIPO_PRODUCTO INT,
	FOREIGN KEY(FK_ID_TIPO_PRODUCTO) REFERENCES TIPO_PRODUCTO(ID_TIPO_PRODUCTO)	
);


CREATE TABLE GUIA (
	ID_GUIA SERIAL PRIMARY KEY,
	TOTAL VARCHAR(200) NULL,
	FECHA DATE NULL,
);

CREATE TABLE DETALLE_GUIA (
	ID_DETALLE SERIAL PRIMARY KEY,
	CANTIDAD INT NULL,
	FECHA DATE NULL,
	FK_ID_PRODUCTO INT,
	FK_ID_GUIA INT,
	FOREIGN KEY(FK_ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
	FOREIGN KEY(FK_ID_GUIA) REFERENCES GUIA(ID_GUIA)
);



-------------------

CREATE TABLE TIPO_DESPACHO (
	ID_TIPO_DESPACHO SERIAL PRIMARY KEY,
	DESCRIPCION VARCHAR(200)
);

CREATE TABLE DESPACHO (
	ID_DESPACHO SERIAL PRIMARY KEY,
	FK_ID_GUIA INT,
	FK_ID_USUARIO_1 INT,
	FK_ID_USUARIO_2 INT,
	FK_ID_RUTA INT,
	FK_ID_CAMION INT,
	FK_ID_TIPO_DESPACHO INT,
	FOREIGN KEY (FK_ID_GUIA) REFERENCES GUIA (ID_GUIA),
	FOREIGN KEY (FK_ID_USUARIO_1) REFERENCES USUARIO (ID_USUARIO),
	FOREIGN KEY (FK_ID_USUARIO_2) REFERENCES USUARIO (ID_USUARIO),
	FOREIGN KEY (FK_ID_RUTA) REFERENCES RUTA (ID_RUTA),
	FOREIGN KEY (FK_ID_CAMION) REFERENCES CAMION (ID_CAMION),
	FOREIGN KEY (FK_ID_TIPO_DESPACHO) REFERENCES TIPO_DESPACHO(ID_TIPO_DESPACHO)

);