--pass pgadmin: jujutsu

CREATE TABLE CAMION (
    ID_CAMION SERIAL PRIMARY KEY,
    PATENTE VARCHAR(10) NOT NULL
);
----------------------------------------

CREATE TABLE CIUDAD (
    ID_CIUDAD SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(200) NOT NULL
);


CREATE TABLE RUTA (
    ID_RUTA SERIAL  PRIMARY KEY,
	DIRECCION VARCHAR (200) NOT NULL,
    DETALLE VARCHAR(200) NULL,
    FK_ID_CIUDAD INT NOT NULL,
    FOREIGN KEY(FK_ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD)

);
------------------------------------------

CREATE TABLE TIPO_USUARIO (
	ID_TIPO_USUARIO SERIAL PRIMARY KEY,
	DESCRIPCION VARCHAR(200) NOT NULL
);


CREATE TABLE USUARIO (
	ID_USUARIO SERIAL PRIMARY KEY,
	RUT VARCHAR(12) NOT NULL,
	NOMBRES VARCHAR(200) NOT NULL,
	APELLIDOS VARCHAR(200) NOT NULL,
	FK_ID_TIPO_USUARIO INT NOT NULL,
	FOREIGN KEY (FK_ID_TIPO_USUARIO) REFERENCES TIPO_USUARIO(ID_TIPO_USUARIO)
);

------------------------------------------

CREATE TABLE TIPO_PRODUCTO (
	ID_TIPO_PRODUCTO SERIAL PRIMARY KEY,
	DETALLE VARCHAR(200)
);


CREATE TABLE PRODUCTO ( 
	ID_PRODUCTO SERIAL PRIMARY KEY,
	DESCRIPCION VARCHAR(200) NOT NULL,
	FK_ID_TIPO_PRODUCTO INT NOT NULL,
	FOREIGN KEY(FK_ID_TIPO_PRODUCTO) REFERENCES TIPO_PRODUCTO(ID_TIPO_PRODUCTO)	
);


CREATE TABLE GUIA (
	ID_GUIA SERIAL PRIMARY KEY,
	TOTAL INT NULL,
	FECHA DATE NULL
);

CREATE TABLE DETALLE_GUIA (
	ID_DETALLE SERIAL PRIMARY KEY,
	CANTIDAD INT NULL,
	FECHA DATE NULL,
	FK_ID_PRODUCTO INT NOT NULL,
	FK_ID_GUIA INT NOT NULL,
	FOREIGN KEY(FK_ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
	FOREIGN KEY(FK_ID_GUIA) REFERENCES GUIA(ID_GUIA)
);



-------------------

CREATE TABLE TIPO_DESPACHO (
	ID_TIPO_DESPACHO SERIAL PRIMARY KEY ,
	DESCRIPCION VARCHAR(200) NOT NULL
);

CREATE TABLE DESPACHO (
	ID_DESPACHO SERIAL PRIMARY KEY,
	ESTADO VARCHAR(50) NOT NULL,
	FK_ID_GUIA INT NOT NULL,
	FK_ID_USUARIO_1 INT NOT NULL,
	FK_ID_USUARIO_2 INT NOT NULL,
	FK_ID_RUTA INT NOT NULL,
	FK_ID_CAMION INT NOT NULL,
	FK_ID_TIPO_DESPACHO INT NOT NULL,
	FOREIGN KEY (FK_ID_GUIA) REFERENCES GUIA (ID_GUIA),
	FOREIGN KEY (FK_ID_USUARIO_1) REFERENCES USUARIO (ID_USUARIO),
	FOREIGN KEY (FK_ID_USUARIO_2) REFERENCES USUARIO (ID_USUARIO),
	FOREIGN KEY (FK_ID_RUTA) REFERENCES RUTA (ID_RUTA),
	FOREIGN KEY (FK_ID_CAMION) REFERENCES CAMION (ID_CAMION),
	FOREIGN KEY (FK_ID_TIPO_DESPACHO) REFERENCES TIPO_DESPACHO(ID_TIPO_DESPACHO),
	CONSTRAINT ESTADO_CHECK CHECK (ESTADO IN ('Entregado','Entregado con devolucion','Rechazado','En camino','En bodega','Indicedente')) 

);


----Para eliminar Estado Check
--ALTER TABLE DESPACHO
--DROP CONSTRAINT ESTADO_CHECK;


----Para añadir Estado Check
--ALTER TABLE DESPACHO
--ADD CONSTRAINT ESTADO_CHECK CHECK (ESTADO IN ('Entregado','Entregado con devolucion','Rechazado','En camino','En bodega','Indicedente'));